# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):
    """Create PostgreSQL schema for inventory domain."""

    initial = True

    dependencies = [
        ('commerce', '0002_models'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS inventory;',
            reverse_sql='DROP SCHEMA IF EXISTS inventory CASCADE;',
        ),
    ]
