# Generated by Django 6.0 on 2025-12-19 15:36

import apps.inventory.models.reservation
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_role_options_and_more'),
        ('commerce', '0002_models'),
        ('inventory', '0001_create_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted', null=True)),
                ('code', models.CharField(help_text='Unique location code within company', max_length=20)),
                ('name', models.CharField(help_text='Location display name', max_length=100)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('virtual', 'Virtual')], default='warehouse', help_text='Type of location', max_length=20)),
                ('address_line1', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Additional address info', max_length=255)),
                ('postal_code', models.CharField(blank=True, help_text='Singapore 6-digit postal code', max_length=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether location is active')),
                ('is_default', models.BooleanField(default=False, help_text='Default location for new inventory')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Location-specific settings')),
                ('company', models.ForeignKey(help_text='Company that owns this location', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': '"inventory"."locations"',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('available_qty', models.PositiveIntegerField(default=0, help_text='Total available quantity')),
                ('reserved_qty', models.PositiveIntegerField(default=0, help_text='Quantity reserved for orders')),
                ('reorder_point', models.PositiveIntegerField(blank=True, help_text='Quantity threshold for reorder alert', null=True)),
                ('reorder_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity to reorder when low', null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Unit cost for this inventory', max_digits=10, null=True)),
                ('last_counted_at', models.DateTimeField(blank=True, help_text='When last physical count was done', null=True)),
                ('last_movement_at', models.DateTimeField(blank=True, help_text='When last stock movement occurred', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version for optimistic locking')),
                ('company', models.ForeignKey(help_text='Company that owns this inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.company')),
                ('product', models.ForeignKey(help_text='Product this inventory is for', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='commerce.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Optional product variant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='commerce.productvariant')),
                ('location', models.ForeignKey(help_text='Location where stock is held', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': '"inventory"."items"',
                'ordering': ['product__name', 'location__code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('damage', 'Damage'), ('count', 'Count')], help_text='Type of stock movement', max_length=30)),
                ('quantity', models.IntegerField(help_text='Quantity change (+in, -out)')),
                ('quantity_before', models.IntegerField(help_text='Available qty before movement')),
                ('quantity_after', models.IntegerField(help_text='Available qty after movement')),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (order, transfer, etc.)', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='ID of referenced document', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Company that owns this movement', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(help_text='Inventory item affected', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': '"inventory"."movements"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='movements_company_0b9918_idx'), models.Index(fields=['inventory_item'], name='movements_invento_215cba_idx'), models.Index(fields=['created_at'], name='movements_created_7b4843_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(help_text='Order this reservation is for')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity reserved')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('expired', 'Expired')], default='pending', help_text='Reservation status', max_length=20)),
                ('expires_at', models.DateTimeField(default=apps.inventory.models.reservation.default_reservation_expiry, help_text='When this reservation expires')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When reservation was confirmed', null=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='When reservation was released', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(help_text='Inventory item being reserved', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Inventory Reservation',
                'verbose_name_plural': 'Inventory Reservations',
                'db_table': '"inventory"."reservations"',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory_item'], name='reservation_invento_9b2012_idx'), models.Index(fields=['order_id'], name='reservation_order_i_ab4cde_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservation_quantity_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company'], name='locations_company_ec14b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['company'], name='items_company_9dcfdc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product'], name='items_product_933cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location'], name='items_locatio_1f2e11_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__lte', models.F('available_qty'))), name='inventory_valid_reserved'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'variant', 'location')},
        ),
    ]
