# Generated by Django 6.0 on 2025-12-20 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_create_schema'),
        ('accounts', '0002_alter_company_options_alter_role_options_and_more'),
        ('commerce', '0002_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique account code within company (e.g., 1000, 1100-001)', max_length=20, validators=[django.core.validators.RegexValidator(message='Account code must be alphanumeric with optional hyphens', regex='^[A-Z0-9\\-]+$')])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=20)),
                ('account_subtype', models.CharField(blank=True, choices=[('current', 'Current Asset'), ('fixed', 'Fixed Asset'), ('intangible', 'Intangible Asset'), ('current_liability', 'Current Liability'), ('long_term', 'Long-term Liability'), ('capital', 'Capital'), ('retained', 'Retained Earnings'), ('operating', 'Operating Revenue'), ('other_income', 'Other Income'), ('cogs', 'Cost of Goods Sold'), ('operating_expense', 'Operating Expense'), ('other_expense', 'Other Expense')], default='', max_length=50)),
                ('gst_code', models.CharField(blank=True, choices=[('SR', 'Standard Rated'), ('ZR', 'Zero Rated'), ('ES', 'Exempt Supply'), ('OS', 'Out of Scope')], default='', help_text='Default GST treatment for transactions on this account', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance (updated when entries are posted)', max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"accounting"."accounts"',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(blank=True, help_text='Reference to source order', null=True)),
                ('invoice_number', models.CharField(help_text='Unique invoice number (e.g., INV-2024-00001)', max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before GST', max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, help_text='GST amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total including GST', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid', max_digits=12)),
                ('peppol_id', models.CharField(blank=True, default='', help_text='PEPPOL invoice identifier', max_length=100)),
                ('peppol_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected')], default='', max_length=20)),
                ('peppol_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('terms', models.TextField(blank=True, default='', help_text='Payment terms and conditions')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer (optional for cash sales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='commerce.customer')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"accounting"."invoices"',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(help_text='Unique entry number within company (e.g., JE-2024-00001)', max_length=50)),
                ('entry_date', models.DateField(help_text='Date of the transaction')),
                ('description', models.TextField(blank=True, default='', help_text='Description of the journal entry')),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('manual', 'Manual Entry'), ('adjustment', 'Adjustment')], default='', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the source document (order, invoice, etc.)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, help_text='Timestamp when entry was posted', null=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'db_table': '"accounting"."journal_entries"',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to debit (must be >= 0)', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to credit (must be >= 0)', max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GST portion of this line (for reporting)', max_digits=10)),
                ('gst_code', models.CharField(blank=True, default='', help_text='GST code for this line', max_length=2)),
                ('description', models.TextField(blank=True, default='', help_text='Line-specific description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account to debit or credit', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'db_table': '"accounting"."journal_lines"',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(help_text='Unique payment number (e.g., PAY-2024-00001)', max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(default='SGD', help_text='ISO 4217 currency code', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paynow', 'PayNow'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('gateway', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('hitpay', 'HitPay'), ('paynow', 'PayNow Corporate'), ('manual', 'Manual')], default='', max_length=50)),
                ('gateway_reference', models.CharField(blank=True, default='', help_text='Payment gateway transaction ID', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failed_reason', models.TextField(blank=True, default='', help_text='Reason for payment failure')),
                ('reference_type', models.CharField(blank=True, choices=[('order', 'Order'), ('invoice', 'Invoice')], default='', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the order or invoice', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment data from gateway')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"accounting"."payments"',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company'], name='accounts_company_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounts_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='account_unique_code_per_company'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company'], name='invoices_company_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='invoices_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'invoice_number'), name='invoice_unique_number_per_company'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company'], name='journals_company_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_date'], name='journals_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='journals_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'entry_number'), name='journal_entry_unique_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(condition=models.Q(('total_debit', models.F('total_credit'))), name='balanced_entry'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['journal_entry'], name='journal_lines_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='journal_lines_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_amount__gt', 0), ('credit_amount', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), _connector='OR'), name='one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0)), name='debit_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0)), name='credit_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company'], name='payments_company_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_type', 'reference_id'], name='payments_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'payment_number'), name='payment_unique_number_per_company'),
        ),
    ]
