"""
Product and ProductVariant models.

Product implements full e-commerce product with:
- DECIMAL pricing fields (financial precision)
- GST code with Singapore tax codes (SR, ZR, ES, OS)
- PostgreSQL tsvector search (DB-generated, read-only)
- JSONB for images and custom attributes
"""
from decimal import Decimal

from django.db import models
from django.conf import settings
from django.contrib.postgres.indexes import GinIndex

from core.models import SoftDeleteModel


# GST code choices matching database schema
GST_CODE_CHOICES = [
    ('SR', 'Standard Rated'),
    ('ZR', 'Zero Rated'),
    ('ES', 'Exempt Supply'),
    ('OS', 'Out of Scope'),
]

# Product status choices
PRODUCT_STATUS_CHOICES = [
    ('draft', 'Draft'),
    ('active', 'Active'),
    ('archived', 'Archived'),
]


class Product(SoftDeleteModel):
    """
    E-commerce product with GST support and full-text search.
    
    All monetary fields use DECIMAL for financial precision.
    tsvector search is generated by PostgreSQL, read-only in Django.
    
    Attributes:
        company: Company that owns this product
        category: Optional category assignment
        sku: Stock keeping unit (unique per company)
        base_price: Main selling price
        gst_code: Singapore GST classification
        gst_rate: Current GST rate (default from settings)
    """
    
    company = models.ForeignKey(
        'accounts.Company',
        on_delete=models.CASCADE,
        related_name='products',
        help_text="Company that owns this product"
    )
    
    category = models.ForeignKey(
        'commerce.Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='products',
        help_text="Product category"
    )
    
    # Identification
    sku = models.CharField(
        max_length=50,
        help_text="Stock Keeping Unit (unique per company)"
    )
    
    barcode = models.CharField(
        max_length=50,
        blank=True,
        help_text="Product barcode (EAN, UPC, etc.)"
    )
    
    # Basic info
    name = models.CharField(
        max_length=200,
        help_text="Product display name"
    )
    
    slug = models.SlugField(
        max_length=200,
        help_text="URL-friendly identifier"
    )
    
    description = models.TextField(
        blank=True,
        help_text="Full product description"
    )
    
    short_description = models.CharField(
        max_length=500,
        blank=True,
        help_text="Brief product summary"
    )
    
    # Pricing (DECIMAL precision critical for financial accuracy)
    base_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text="Base selling price in SGD"
    )
    
    cost_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Cost price for margin calculation"
    )
    
    compare_at_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Original price for showing discounts"
    )
    
    # GST (Singapore tax)
    gst_code = models.CharField(
        max_length=2,
        choices=GST_CODE_CHOICES,
        default='SR',
        help_text="Singapore GST classification code"
    )
    
    gst_rate = models.DecimalField(
        max_digits=5,
        decimal_places=4,
        default=Decimal('0.09'),
        help_text="GST rate (default 9% for SR)"
    )
    
    # Physical dimensions
    weight_grams = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Product weight in grams"
    )
    
    length_cm = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Length in centimeters"
    )
    
    width_cm = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Width in centimeters"
    )
    
    height_cm = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Height in centimeters"
    )
    
    # Inventory settings
    track_inventory = models.BooleanField(
        default=True,
        help_text="Whether to track stock levels"
    )
    
    allow_backorder = models.BooleanField(
        default=False,
        help_text="Allow orders when out of stock"
    )
    
    low_stock_threshold = models.PositiveIntegerField(
        default=10,
        help_text="Alert threshold for low stock"
    )
    
    # Status
    status = models.CharField(
        max_length=20,
        choices=PRODUCT_STATUS_CHOICES,
        default='draft',
        help_text="Product visibility status"
    )
    
    # Media (JSONB array of image URLs)
    images = models.JSONField(
        default=list,
        blank=True,
        help_text="List of product image URLs"
    )
    
    # SEO
    meta_title = models.CharField(
        max_length=70,
        blank=True,
        help_text="SEO title"
    )
    
    meta_description = models.CharField(
        max_length=160,
        blank=True,
        help_text="SEO meta description"
    )
    
    # Custom attributes (JSONB for flexibility)
    attributes = models.JSONField(
        default=dict,
        blank=True,
        help_text="Custom product attributes as key-value pairs"
    )
    
    class Meta:
        db_table = '"commerce"."products"'
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ['-created_at']
        unique_together = [('company', 'sku')]
        indexes = [
            models.Index(fields=['company']),
            models.Index(fields=['category']),
            models.Index(fields=['company', 'status']),
            models.Index(fields=['sku']),
            # Note: GIN index on search_vector created via raw SQL migration
        ]
    
    def __str__(self):
        return f"{self.sku} - {self.name}"
    
    @property
    def effective_price(self) -> Decimal:
        """
        Get the effective selling price.
        
        Returns base_price (compare_at_price is for display only).
        """
        return self.base_price
    
    @property
    def is_on_sale(self) -> bool:
        """Check if product has a discount (compare_at_price > base_price)."""
        if self.compare_at_price is None:
            return False
        return self.compare_at_price > self.base_price
    
    @property
    def discount_percentage(self) -> Decimal:
        """Calculate discount percentage if on sale."""
        if not self.is_on_sale:
            return Decimal('0')
        discount = (self.compare_at_price - self.base_price) / self.compare_at_price * 100
        return round(discount, 0)
    
    @property
    def margin_percentage(self) -> Decimal | None:
        """Calculate profit margin percentage."""
        if self.cost_price is None or self.cost_price == 0:
            return None
        margin = (self.base_price - self.cost_price) / self.base_price * 100
        return round(margin, 2)
    
    def calculate_gst(self, quantity: int = 1) -> tuple[Decimal, Decimal, Decimal]:
        """
        Calculate price breakdown with GST.
        
        Args:
            quantity: Number of items
            
        Returns:
            Tuple of (subtotal, gst_amount, total)
        """
        subtotal = self.base_price * quantity
        
        if self.gst_code == 'SR':
            gst_amount = round(subtotal * self.gst_rate, 2)
        else:
            gst_amount = Decimal('0.00')
        
        total = subtotal + gst_amount
        return subtotal, gst_amount, total
    
    @property
    def primary_image(self) -> str | None:
        """Get the first image URL or None."""
        if self.images and len(self.images) > 0:
            return self.images[0]
        return None


class ProductVariant(models.Model):
    """
    Product variant for different options (size, color, etc).
    
    Variants have their own SKU and can adjust the base price.
    Options stored as JSONB for flexibility.
    
    Example options: {"size": "M", "color": "Blue"}
    """
    
    id = models.UUIDField(
        primary_key=True,
        default=None,
        editable=False
    )
    
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='variants',
        help_text="Parent product"
    )
    
    sku = models.CharField(
        max_length=50,
        unique=True,
        help_text="Variant SKU (globally unique)"
    )
    
    barcode = models.CharField(
        max_length=50,
        blank=True,
        help_text="Variant barcode"
    )
    
    name = models.CharField(
        max_length=200,
        blank=True,
        help_text="Optional variant name"
    )
    
    # Variant options as JSONB
    options = models.JSONField(
        default=dict,
        blank=True,
        help_text="Variant options (e.g., {'size': 'M', 'color': 'Blue'})"
    )
    
    # Price adjustment (added to product.base_price)
    price_adjustment = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text="Price adjustment from base price (can be negative)"
    )
    
    weight_grams = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text="Override weight for this variant"
    )
    
    is_active = models.BooleanField(
        default=True,
        help_text="Whether variant is available"
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = '"commerce"."product_variants"'
        verbose_name = 'Product Variant'
        verbose_name_plural = 'Product Variants'
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['product']),
        ]
    
    def __str__(self):
        if self.name:
            return f"{self.product.name} - {self.name}"
        return f"{self.product.name} ({self.sku})"
    
    def save(self, *args, **kwargs):
        """Generate UUID if not set."""
        if self.id is None:
            import uuid
            self.id = uuid.uuid4()
        super().save(*args, **kwargs)
    
    @property
    def effective_price(self) -> Decimal:
        """
        Calculate effective price (base + adjustment).
        """
        return self.product.base_price + self.price_adjustment
    
    @property
    def options_display(self) -> str:
        """
        Get human-readable options string.
        
        Example: "Size: M, Color: Blue"
        """
        if not self.options:
            return ""
        return ", ".join(f"{k}: {v}" for k, v in self.options.items())
