# Generated by Django 6.0 on 2025-12-19 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='SG', help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Primary contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Is the company registered for GST?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_registration_date',
            field=models.DateField(blank=True, help_text='Date of GST registration', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_registration_number',
            field=models.CharField(blank=True, help_text='GST registration number (if registered)', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered legal name', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Trading name', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[0-9]{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='plan_tier',
            field=models.CharField(choices=[('lite', 'Lite (Free)'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='lite', help_text='Subscription plan tier', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Singapore postal code (6 digits)', max_length=6),
        ),
        migrations.AlterField(
            model_name='company',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Company-specific settings'),
        ),
        migrations.AlterField(
            model_name='company',
            name='uen',
            field=models.CharField(help_text='Singapore Unique Entity Number (e.g., 201812345A)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Singapore UEN (e.g., 201812345A)', regex='^[0-9]{8,9}[A-Za-z]$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this role belongs to (null for system roles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Whether this is a built-in system role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Role name (e.g., 'admin', 'finance')", max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of permission strings'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address (used for login)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether user can log in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email has been verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this time', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, help_text='Multi-factor authentication enabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, help_text='TOTP secret for MFA', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_hash', help_text='Hashed password', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[0-9]{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this role was assigned'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was created'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['uen'], name='companies_uen_0f10ff_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['gst_registered'], name='companies_gst_reg_7aa32b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company'], name='users_company_c76839_idx'),
        ),
    ]
