# Generated by Django 6.0 on 2025-12-19 14:55

from django.db import migrations


class Migration(migrations.Migration):
    """Create PostgreSQL schema for commerce domain."""

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS commerce;',
            reverse_sql='DROP SCHEMA IF EXISTS commerce CASCADE;',
        ),
    ]
